module.exports = {
  apps: [
    {
      name: 'telegram-bot-server',
      script: './bin/server',
      cwd: './',
      env: {
        PORT: 3001,
        GIN_MODE: 'release',
        DB_DRIVER: 'sqlite',
        DB_DSN: './data/prod.db',
        JWT_SECRET: process.env.JWT_SECRET || 'your-super-secret-jwt-key-change-this-in-production',
        JWT_EXPIRY: '168h',
        TELEGRAM_BOT_TOKEN: process.env.TELEGRAM_BOT_TOKEN,
        ALLOWED_ORIGINS: 'https://istias.studio,https://www.istias.studio,https://dash.istias.studio',
      },
      watch: false,
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      error_file: './logs/server-error.log',
      out_file: './logs/server-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
    {
      name: 'telegram-mini-app',
      script: 'npm',
      args: 'run preview -- --host 0.0.0.0 --port 4173',
      cwd: './mini-app',
      env: {
        NODE_ENV: 'production',
      },
      watch: false,
      instances: 1,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      error_file: './logs/mini-app-error.log',
      out_file: './logs/mini-app-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    },
  ],
};
